### ISSUE TITLE
The secret key is not protected by Intel SGX enclave

### ISSUE THREAD

**Issue by jmp0x7c00** [ayeks/TresorSGX#6]
The key is defined in the app code, not in the enclave code, so it is not protected by SGX and can be obtained by an attacker.

in file `tresorencl/tresorencl_tester.c`:

```
unsigned char test_key_128[16] =      {	0x2b,0x7e,0x15,0x16,0x28,0xae,0xd2,0xa6,0xab,0xf7,0x15,0x88,0x09,0xcf,0x4f,0x3c};
*/

unsigned char test_key_128[16] = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f";

```

**Comment by ayeks** [comment]
Jes it is because it is a test script. Checkout its Readme: https://github.com/ayeks/TresorSGX/tree/master/tresorencl#readme
